import React, { useState } from 'react';
import {
  Sparkles,
  ArrowLeft,
  CheckCircle2,
  AlertTriangle,
  Award,
  Users,
  Timer,
  Flame,
  RotateCcw,
  BookOpen
} from 'lucide-react';
import { omniPlayLearnService } from '../../../../sdk/browser-services/OmniPlayLearnService';

interface OmniTriviaFamilyGameProps {
  onBack: () => void;
  onComplete?: (score: number) => void;
}

interface TriviaQuestion {
  id: string;
  category: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
}

const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  {
    id: 'q1',
    category: 'Computer Science History',
    question: 'Who is widely considered the world’s first computer programmer for developing an algorithm for Charles Babbage’s Mechanical Analytical Engine?',
    options: ['Ada Lovelace', 'Alan Turing', 'Grace Hopper', 'Claude Shannon'],
    correctIndex: 0,
    explanation: 'Ada Lovelace published the first algorithm intended to be carried out by a machine in 1843, recognizing computers could manipulate symbols beyond numbers.',
    difficulty: 'Easy'
  },
  {
    id: 'q2',
    category: 'Cryptography & Privacy',
    question: 'What type of mathematical structure makes NIST Post-Quantum ML-KEM algorithms resistant to quantum Shor algorithm attacks?',
    options: ['Elliptic Curves', 'High-Dimensional Polynomial Lattices', 'Prime Factorization Rings', 'Discrete Logarithms'],
    correctIndex: 1,
    explanation: 'High-dimensional lattice vector problems (Module-LWE) have no known efficient polynomial-time quantum algorithms.',
    difficulty: 'Medium'
  },
  {
    id: 'q3',
    category: 'Hardware & Silicon',
    question: 'What does "TDP" stand for in hardware and microprocessor specifications?',
    options: ['Thermal Design Power', 'Total Data Processing', 'Transistor Density Pitch', 'Tensor Direct Pipeline'],
    correctIndex: 0,
    explanation: 'Thermal Design Power represents the maximum amount of heat generated by a computer chip that the cooling system is designed to dissipate.',
    difficulty: 'Easy'
  },
  {
    id: 'q4',
    category: 'Internet Architecture',
    question: 'In TCP/IP networking, which protocol provides cryptographically verified and tamper-proof domain name resolutions?',
    options: ['DNS-over-HTTPS (DoH) / DNSSEC', 'BGP Anycast', 'HTTP/3 Quic', 'DHCP Snooping'],
    correctIndex: 0,
    explanation: 'DNSSEC provides cryptographic validation of DNS queries, and DoH encrypts queries over HTTPS to prevent ISP surveillance.',
    difficulty: 'Medium'
  },
  {
    id: 'q5',
    category: 'Artificial Intelligence',
    question: 'What is the primary memory bottleneck during long-context LLM token generation that PagedAttention solves?',
    options: ['KV (Key-Value) Cache Memory Fragmentation', 'Integer Weight Quantization', 'Embedding Layer Dropout', 'Token Vocabulary Lookup'],
    correctIndex: 0,
    explanation: 'KV cache tensors grow dynamically per request; PagedAttention partitions this memory into non-contiguous pages like virtual OS memory to avoid fragmentation.',
    difficulty: 'Hard'
  }
];

export const OmniTriviaFamilyGame: React.FC<OmniTriviaFamilyGameProps> = ({ onBack, onComplete }) => {
  const [currentIdx, setCurrentIdx] = useState(0);
  const [selectedOption, setSelectedOption] = useState<number | null>(null);
  const [isAnswerSubmitted, setIsAnswerSubmitted] = useState(false);
  const [score, setScore] = useState(0);
  const [streak, setStreak] = useState(1);
  const [players, setPlayers] = useState(['Player 1', 'Player 2']);
  const [activePlayerIdx, setActivePlayerIdx] = useState(0);
  const [isGameOver, setIsGameOver] = useState(false);

  const q = TRIVIA_QUESTIONS[currentIdx];

  const handleSelectOption = (idx: number) => {
    if (isAnswerSubmitted) return;
    setSelectedOption(idx);
  };

  const handleSubmitAnswer = () => {
    if (selectedOption === null || isAnswerSubmitted) return;
    setIsAnswerSubmitted(true);

    const isCorrect = selectedOption === q.correctIndex;
    if (isCorrect) {
      const addedPoints = (q.difficulty === 'Easy' ? 100 : q.difficulty === 'Medium' ? 200 : 300) * streak;
      setScore(prev => prev + addedPoints);
      setStreak(prev => prev + 1);
    } else {
      setStreak(1);
    }
  };

  const handleNextQuestion = () => {
    if (currentIdx < TRIVIA_QUESTIONS.length - 1) {
      setCurrentIdx(prev => prev + 1);
      setSelectedOption(null);
      setIsAnswerSubmitted(false);
      setActivePlayerIdx(prev => (prev + 1) % players.length);
    } else {
      setIsGameOver(true);
      omniPlayLearnService.unlockAchievement('ach_learning_streak');
      if (onComplete) onComplete(score);
    }
  };

  const handleRestart = () => {
    setCurrentIdx(0);
    setSelectedOption(null);
    setIsAnswerSubmitted(false);
    setScore(0);
    setStreak(1);
    setIsGameOver(false);
  };

  return (
    <div id="omni-trivia-family-game" className="p-6 rounded-3xl bg-stone-900/90 border border-stone-800 space-y-6 max-w-2xl mx-auto shadow-2xl">
      {/* Header */}
      <div className="flex items-center justify-between pb-4 border-b border-stone-800">
        <button
          onClick={onBack}
          className="flex items-center gap-2 px-3 py-1.5 rounded-xl bg-stone-950 hover:bg-stone-800 text-stone-300 text-xs font-semibold border border-stone-700 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back to Hub</span>
        </button>

        <div className="flex items-center gap-3">
          <div className="flex items-center gap-1 text-xs text-amber-400 font-bold bg-amber-950/60 px-3 py-1 rounded-xl border border-amber-800">
            <Flame className="w-4 h-4" />
            <span>{streak}x Multiplier</span>
          </div>

          <div className="text-xs font-mono font-bold text-emerald-400 bg-emerald-950/60 px-3 py-1 rounded-xl border border-emerald-800">
            Score: {score} XP
          </div>
        </div>
      </div>

      {isGameOver ? (
        /* Game Over Screen */
        <div className="text-center py-8 space-y-4">
          <div className="w-16 h-16 rounded-full bg-amber-500/20 border border-amber-500 flex items-center justify-center mx-auto text-amber-400 shadow-xl">
            <Award className="w-8 h-8" />
          </div>
          <div className="space-y-1">
            <h3 className="text-xl font-extrabold text-white">Trivia Round Complete!</h3>
            <p className="text-xs text-stone-400">
              Outstanding performance across Science, Computing & Cryptography rounds!
            </p>
          </div>
          <div className="p-4 rounded-2xl bg-stone-950 border border-stone-800 max-w-xs mx-auto text-center font-mono">
            <span className="text-xs text-stone-500">Total Points Earned:</span>
            <div className="text-3xl font-black text-emerald-400">{score} XP</div>
          </div>
          <button
            onClick={handleRestart}
            className="px-6 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs shadow-lg transition-colors"
          >
            Play Another Round
          </button>
        </div>
      ) : (
        /* Question Round */
        <div className="space-y-6">
          {/* Question Metadata */}
          <div className="flex items-center justify-between text-xs text-stone-400">
            <span className="px-2.5 py-1 rounded-lg bg-indigo-950 text-indigo-300 font-semibold border border-indigo-800">
              {q.category}
            </span>
            <div className="flex items-center gap-2">
              <Users className="w-3.5 h-3.5 text-cyan-400" />
              <span className="font-bold text-stone-300">Turn: {players[activePlayerIdx]}</span>
              <span>•</span>
              <span>Q {currentIdx + 1} of {TRIVIA_QUESTIONS.length}</span>
            </div>
          </div>

          {/* Question Heading */}
          <h3 className="text-base font-bold text-stone-100 leading-snug">
            {q.question}
          </h3>

          {/* Options Grid */}
          <div className="space-y-2.5">
            {q.options.map((opt, idx) => {
              const isSelected = selectedOption === idx;
              const isCorrect = isAnswerSubmitted && idx === q.correctIndex;
              const isWrong = isAnswerSubmitted && isSelected && idx !== q.correctIndex;

              return (
                <button
                  key={idx}
                  onClick={() => handleSelectOption(idx)}
                  className={`w-full p-3.5 rounded-2xl text-left text-xs font-semibold flex items-center justify-between transition-all ${
                    isCorrect
                      ? 'bg-emerald-950/80 border-2 border-emerald-500 text-emerald-200'
                      : isWrong
                      ? 'bg-rose-950/80 border-2 border-rose-500 text-rose-200'
                      : isSelected
                      ? 'bg-indigo-950 border-2 border-indigo-500 text-white'
                      : 'bg-stone-950 border border-stone-800 text-stone-300 hover:bg-stone-800/80'
                  }`}
                >
                  <div className="flex items-center gap-3">
                    <span className="w-6 h-6 rounded-lg bg-stone-900 border border-stone-700 flex items-center justify-center font-mono text-[11px]">
                      {String.fromCharCode(65 + idx)}
                    </span>
                    <span>{opt}</span>
                  </div>

                  {isCorrect && <CheckCircle2 className="w-4 h-4 text-emerald-400" />}
                  {isWrong && <AlertTriangle className="w-4 h-4 text-rose-400" />}
                </button>
              );
            })}
          </div>

          {/* Educational Explanation Box */}
          {isAnswerSubmitted && (
            <div className="p-4 rounded-2xl bg-stone-950 border border-stone-800 space-y-2 text-xs">
              <div className="flex items-center gap-1.5 font-bold text-indigo-400 uppercase tracking-wider text-[11px]">
                <BookOpen className="w-3.5 h-3.5" />
                <span>Historical & Technical Insight</span>
              </div>
              <p className="text-stone-300 leading-relaxed">
                {q.explanation}
              </p>
            </div>
          )}

          {/* Action Button */}
          <div className="flex justify-end pt-2">
            {!isAnswerSubmitted ? (
              <button
                onClick={handleSubmitAnswer}
                disabled={selectedOption === null}
                className="px-5 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white font-bold text-xs shadow-md transition-colors"
              >
                Submit Answer
              </button>
            ) : (
              <button
                onClick={handleNextQuestion}
                className="px-5 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs shadow-md transition-colors"
              >
                {currentIdx < TRIVIA_QUESTIONS.length - 1 ? 'Next Question →' : 'View Results'}
              </button>
            )}
          </div>
        </div>
      )}
    </div>
  );
};
